# Pre-requisite: ansible-galaxy collection install community.libvirt
#
- hosts: satellite

  name: Register Satellite, install RHEL system roles, unregister
  gather_facts: yes
  become: yes

  vars:

    rhel_version: "{{ ansible_facts['distribution_version'] }}"

  tasks:

  - name: Show the RHEL version
    debug:
      msg: RHEL version {{ rhel_version }}
    tags:
    - debug

  - name: Register the systems with subscription-manager
    redhat_subscription:
      state: present
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
    tags:
      - subscription-manager

  - name: Enable a rhel-7-server-extras-rpms repository
    community.general.rhsm_repository:
      name: rhel-7-server-extras-rpms

  - name: Install the rhel-system-roles package via satellite-maintain (takes several minutes)
    shell:
      cmd: "satellite-maintain packages install -y rhel-system-roles"

  - name: Unregister the systems with subscription-manager
    redhat_subscription:
      state: absent
    tags:
      - subscription-manager
