---
- hosts: satellite

  name: Configure RHEL hosts for Remote Execution (REX) from Satellite
  gather_facts: yes
  become: yes

  vars:

    rhel_version: "{{ ansible_facts['distribution_version'] }}"
      #rhel_version: "{{ ansible_facts['distribution_major_version'] }}"

  vars_files:
    - vars/main.yml

  tasks:

  - name: Show the RHEL version
    debug:
      msg: RHEL version {{ rhel_version }}
    tags:
    - debug

  - name: Configure Satellite for Remote Execution
    theforeman.foreman.setting:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      username: "{{ satellite_username }}"
      password: "{{ satellite_password }}"
      server_url: "{{ satellite_server_url }}"
    loop:
      - { name: 'remote_execution_by_default', value: 'true' }
      - { name: 'errata_status_installable', value: 'true' }
      - { name: 'remote_execution_ssh_user', value: 'rexuser' }
    tags:
      - satellite_settings
