---
- hosts: satellite.example.com

  name: Register Satellite, install RHEL system roles, unregister
  # Based on instructions here: 
  # https://www.redhat.com/en/blog/satellite-host-configuration-rhel-system-roles-powered-ansible
  # or
  # https://www.jazakallah.info/post/how-to-use-ansible-roles-for-remote-management-from-satellite-server

  gather_facts: no

  tasks:

  - name: Register the systems with subscription-manager
    redhat_subscription:
      state: present
      #username: "{{ rhn_username }}"
      #password: "{{ rhn_password }}"
      activationkey: "{{ rhn_activation_key }}"
      org_id: "{{ rhn_org_id }}"
    tags:
      - subscription-manager

  #- name: Enable a rhel-7-server-extras-rpms repository
  #  community.general.rhsm_repository:
  #    name: rhel-7-server-extras-rpms

  - name: Install the rhel-system-roles package
    yum:
      name: rhel-system-roles
      state: present
      disable_plugin: foreman-protector

  - name: Unregister the systems with subscription-manager
    redhat_subscription:
      state: absent
    tags:
      - subscription-manager
