# Pre-requisite: ansible-galaxy collection install community.libvirt
#
- hosts: localhost
  connection: local

  name: Register Satellite, install RHEL system roles, unregister
  gather_facts: no

  vars:

    login: &login
      server_url: "{{ lookup('env', 'FOREMAN_SERVER') }}"
      username: "{{ lookup('env', 'FOREMAN_USER') }}"
      password: "{{ lookup('env', 'FOREMAN_PASSWORD') }}"
      validate_certs: no

  tasks:

  - name: Register the systems with subscription-manager
    redhat_subscription:
      state: present
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
    tags:
      - subscription-manager

  - name: Enable a rhel-7-server-extras-rpms repository
    community.general.rhsm_repository:
      name: rhel-7-server-extras-rpms

  - name: Install the rhel-system-roles package
    yum:
      name: rhel-system-roles
      state: present
      disable_plugin: foreman-protector

  - name: Unregister the systems with subscription-manager
    redhat_subscription:
      state: absent
    tags:
      - subscription-manager
