---
- hosts: localhost
  connection: local

  name: Configure RHEL hosts for Remote Execution (REX) from Satellite
  gather_facts: no

  vars:
    login: &login
      server_url: "{{ lookup('env', 'SATELLITE_SERVER_URL') }}"
      username: "{{ lookup('env', 'SATELLITE_USERNAME') }}"
      password: "{{ lookup('env', 'SATELLITE_PASSWORD') }}"
      validate_certs: "{{ lookup('env', 'SATELLITE_VALIDATE_CERTS') }}"
  tasks:

  - name: Configure Satellite for Remote Execution
    theforeman.foreman.setting:
      <<: *login
      name: "{{ item.name }}"
      value: "{{ item.value }}"
    loop:
      - { name: 'remote_execution_by_default', value: 'true' }
      - { name: 'errata_status_installable', value: 'true' }
      - { name: 'remote_execution_ssh_user', value: 'rexuser' }
    tags:
      - satellite_settings
